Added custom fan control

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -4,6 +4,13 @@ set -e
 if [ "$1" = "configure" ]; then
     systemctl enable getty@tty1.service || true
     chmod +x /usr/sbin/pswpci.sh
+    echo "Compiling Device Tree Overlay..."
+    if [ -f /boot/overlay-user/rk3588-opi5plus-fan-custom.dts ]; then
+        dtc -O dtb -o /boot/overlay-user/rk3588-opi5plus-fan-custom.dtbo /boot/overlay-user/rk3588-opi5plus-fan-custom.dts
+        echo "Overlay compiled successfully."
+    else
+        echo "Warning: .dts file not found in /boot/overlay-user/"
+    fi
     ENV_FILE="/boot/armbianEnv.txt"
     if [ -f "$ENV_FILE" ]; then
         if grep -q "^extraargs=" "$ENV_FILE"; then
@@ -21,6 +28,13 @@ if [ "$1" = "configure" ]; then
             if ! grep -q "panthor-gpu" <<< "$(grep "^overlays=" "$ENV_FILE")"; then
                 sed -i '/^overlays=/ s/$/ panthor-gpu/' "$ENV_FILE"
             fi
+        fi
+        if grep -q "user_overlays=" "$ENV_FILE"; then
+            if ! grep -q "rk3588-opi5plus-fan-custom" "$ENV_FILE"; then
+                sed -i '/^user_overlays=/ s/$/ rk3588-opi5plus-fan-custom/' "$ENV_FILE"
+            fi
+        else
+            echo "user_overlays=rk3588-opi5plus-fan-custom" >> "$ENV_FILE"
         fi
         if ! grep -q "^earlycon=" "$ENV_FILE"; then
             echo "earlycon=on" >> "$ENV_FILE"
